### ISSUE TITLE
No files found "toolchain/Config.in"

### ISSUE THREAD

**Issue by hzjnet** [SVoxel/R7800#4]
make menuconfig
Config.in:487: warning: deprecated 'depends' syntax, use 'depends on' instead.
Config.in:495: warning: deprecated 'depends' syntax, use 'depends on' instead.
Config.in:652: glob failed: No files found "toolchain/Config.in"
make: *** [menuconfig] Error 1

 ./scripts/feeds update
Unable to open feeds configuration at ./scripts/feeds line 39.
 ./scripts/feeds install
Unable to open feeds configuration at ./scripts/feeds line 39.

how can I get toolchain ?     thank you

**Comment by SVoxel** [comment]
You can extract toolchain for example from GPL sources of the stock firmware. Latest:

https://www.downloads.netgear.com/files/GPL/R7800-V1.0.2.68_gpl_src.tar.bz2.zip

Voxel.

**Comment by hzjnet** [comment]
now,we feeds ok：
SVoxel-R7800]$ ./scripts/feeds update ;./scripts/feeds install
Updating feed 'packages' from '../qca/feeds/packages' ...
Create index file './feeds/packages.index' 
Updating feed 'networking' from '../qca/feeds/networking' ...
Create index file './feeds/networking.index' 
Updating feed 'luci' from '../qca/feeds/luci' ...
..............................................
Create index file './feeds/adk.index' 
Updating feed 'adsprpc' from '../qca/feeds/adsprpc' ...
Create index file './feeds/adsprpc.index' 
Updating feed 'data_modem_monitor' from '../qca/feeds/data-modem-monitor' ...
Create index file './feeds/data_modem_monitor.index' 

but can't find toolchain ！I want to build it ,how can I get toolchain ?  can you  help me ?   
                    thank you

**Comment by SVoxel** [comment]
As I said, you can create your toolchain yourself. Download toolchain used by NG from the NETGEAR GPL sources, see above. After that you should be able to modify it cloning OpenWRT toolchain

https://github.com/openwrt/openwrt

using compiler you like. GCC 5.5.0 or 7.5.0 or 8.4.0 or 9.3.0 and leaving uClibc from NG.

Voxel.

**Comment by hzjnet** [comment]
> You can extract toolchain for example from GPL sources of the stock firmware. Latest:
> 
> https://www.downloads.netgear.com/files/GPL/R7800-V1.0.2.68_gpl_src.tar.bz2.zip
> 
> Voxel.

think you
I get tools&toolchain from  R7800-V1.0.2.68_gpl_src.tar.bz2.zip 
bu I cann.t get something 
    ssh://qca-git01.qualcomm.com source program
1 for example :PKG_SOURCE_URL:=*_*ssh://qca-git01.qualcomm.com*_*:29418/streamboost/angular-ozker

2 make menuconfig V=s
............
tmp/.config-package.in:15542: warning: deprecated 'depends' syntax, use 'depends on' instead.
tmp/.config-package.in:15755: warning: deprecated 'depends' syntax, use 'depends on' instead.
make: *** [menuconfig] Error 1

my evn as follws:
 $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.4' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4) 

 $ lsb_release -ra
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty
